<?php


namespace Drupal\organization\Form;

use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_plus\Entity\ContentEntityForm;

abstract class BusinessGroupEntityForm extends ContentEntityForm {

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form = parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub

    $entity = $this->entity;

    $form['business_group']['#disabled'] = !$entity->isNew();

    return $form;
  }

}
