<?php

/**
 * @file
 * Contains dsi_contract.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dsi_contract_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_contract module.
    case 'help.page.dsi_contract':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The contracts.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function dsi_contract_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'dsi_client') {
    $fields = [];
    // @deprecated in later version.
    $fields['contract'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Contract'))
      ->setSetting('target_type', 'dsi_contract')
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => 6,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
    return $fields;
  }
}
