<?php

/**
 * @file
 * Contains dsi_lawyer.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dsi_client\Entity\ClientType;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function dsi_lawyer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_lawyer module.
    case 'help.page.dsi_lawyer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The lawyer industry') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function dsi_lawyer_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'dsi_record') {
    $fields['name']->setRequired(FALSE);
    $fields['detail']->setRequired(TRUE);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() on record.
 */
function dsi_lawyer_dsi_record_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $description = $entity->get('detail')->value;
  $entity->set('name', mb_substr($description, 0, 60));
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dsi_lawyer_form_dsi_record_add_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  unset($form['name']);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dsi_lawyer_form_dsi_record_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  unset($form['name']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dsi_lawyer_form_dsi_client_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\dsi_client\Entity\ClientInterface $client */
  $client = $form_state->getFormObject()->getEntity();
  if (!$client->isNew()) {
    $form['customer_source']['#disabled'] = TRUE;
  }
  $form['client_type']['phone']['widget'][0]['value']['#disabled'] = TRUE;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function dsi_lawyer_entity_extra_field_info() {
  $extra = [];

  foreach (ClientType::loadMultiple() as $bundle) {
    $extra['dsi_client'][$bundle->id()]['display']['entity_record'] = [
      'label' => t('Entity record'),
      'description' => 'Record by entity type and entity id',
      'weight' => 10,
    ];
    $extra['dsi_client'][$bundle->id()]['display']['entity_contract'] = [
      'label' => t('Entity contract'),
      'description' => 'Contract by entity type and entity id',
      'weight' => 10,
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view() for dsi_client.
 */
function dsi_lawyer_dsi_client_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('entity_record')) {
    $build['entity_record'] = views_embed_view('entity_record', 'default', $entity->getEntityTypeId(), $entity->id());
  }
  if ($display->getComponent('entity_contract')) {
    $build['entity_contract'] = views_embed_view('entity_contract', 'default',$entity->id());
  }
}
