<?php

/**
 * @file
 * Contains languagechinese.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function languagechinese_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the languagechinese module.
    case 'help.page.languagechinese':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The translation for chinese.') . '</p>';
      return $output;

    default:
  }
}
