<?php

/**
 * @file
 * Contains dsi_contract.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function dsi_contract_theme() {
  $theme = [];
  $theme['dsi_contract_form'] = [
    'render element' => 'form',
  ];
  return $theme;
}

/**
 * Implements hook_help().
 */
function dsi_contract_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_contract module.
    case 'help.page.dsi_contract':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The contracts.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function dsi_contract_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'dsi_client') {
    $fields = [];
    $fields['contract'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Contract'))
      ->setSetting('target_type', 'dsi_contract')
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => 6,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 6,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    return $fields;
  }
}

/**
 * Implements hook_entity_operation().
 */
function dsi_contract_entity_operation(EntityInterface $entity) {
  $operations = [];
  switch ($entity->getEntityTypeId()) {
    case 'dsi_client':
      $operations['contract'] = [
        'title' => t('+合同'),
        'url' => Url::fromRoute('entity.dsi_contract.add_contract', [
          'dsi_client' => $entity->id(),
        ],
          [
            'attributes' => [
              'class' => [
                'use-ajax',
              ],
              'data-dialog-type' => 'modal',
              'data-dialog-options' => '{"width": "80%"}',
            ],
            'query' => \Drupal::destination()->getAsArray(),
          ]
        ),
        'weight' => 0,
      ];
      break;
  }

  return $operations;
}
