<?php

/**
 * @file
 * Contains dsi_commerce_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dsi_commerce_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_commerce_demo module.
    case 'help.page.dsi_commerce_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The demo commerce for dsi.') . '</p>';
      return $output;

    default:
  }
}
