<?php

/**
 * Implements hook_navbar_user_block_item().
 */
function dsi_color_user_navbar_user_block_item() {
  $build['navbar_user'] = [
    '#theme' => 'navbar_user',
    '#attributes' => [
      'class' => [
        'ttttt',
      ],
    ],
    '#content' => [
      'item' => ['#markup' => 'xxx'],
    ],
  ];
  return $build;
}

/**
 * Implements hook_theme().
 */
function dsi_color_user_theme($existing, $type, $theme, $path) {
  return [
    'navbar_user' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
