<?php

/**
 * Implements hook_theme().
 */
function dsi_color_user_theme($existing, $type, $theme, $path) {
  return [
    'navbar_user' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_navbar_user_block_item().
 */
function dsi_color_user_navbar_user_block_item() {
  $build = \Drupal::service('plugin.manager.block')->createInstance('avatar_block')->build();
  return $build;
}
