<?php

/**
 * @file
 * Contains dsi_cases.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dsi_cases_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_cases module.
    case 'help.page.dsi_cases':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The lawyer of cases.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu__role_menu.
 */
function dsi_cases_preprocess_menu__role_menu(&$variables) {
  $icons = [
    'entity.dsi_cases.collection' => 'iconfont icon-anjian1',
  ];
  _eabax_core_set_menu_items_icon($variables['items'], $icons);
}
