<?php

/**
 * @file
 * SUBTHEME theme file.
 */


/**
 * Implements hook_preprocess_HOOK() for menu__role_menu.
 */
function dsi_color_preprocess_menu__role_menu(&$variables) {
  $icons = [
    'entity.dsi_client.collection' => 'iconfont icon-kehu4',
    'entity.dsi_cases.collection' => 'iconfont icon-anjian1',
    'entity.dsi_record.collection' => 'iconfont icon-rili',
  ];
 _eabax_core_set_menu_items_icon($variables['items'], $icons);
}
