# Schema for the configuration files of the dsi_client module.
dsi_client.settings:
  type: config_object
  label: 'Client settings'
  mapping:
    encoding_rules:
      type: string
      label: 'Encoding rules'
