# Schema for the configuration files of the dsi_client module.
dsi_client.settings:
  type: config_object
  label: 'Client settings'
  mapping:
    encoding_rules:
      type: string
      label: 'Encoding rules'
    polling:
      type: sequence
      label: 'Polling'
      sequence:
        type: mapping
        label: 'Polling'
        mapping:
          current:
            type: integer
            label: 'Current'
          business_group:
            type: integer
            label: 'Business group'
          person:
            type: sequence
            label: 'Person'
            sequence:
              type: integer
              label: 'Person'
