<?php

/**
 * @file
 * Contains dsi_color_block.module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_help().
 */
function dsi_color_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_color_block module.
    case 'help.page.dsi_color_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The extension block for color theme.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dsi_color_block_theme($existing, $type, $theme, $path) {
  return [
    'theme_panel_block' => [
      'variables' => [
        'content' => NULL
      ],
    ],
    'navbar_user_block' => [
      'variables' => [
        'content' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_block_access().
 */
function dsi_color_block_block_access(Block $block, $operation, AccountInterface $account) {
  $plugin_id = $block->getPluginId();
  if (in_array($plugin_id, ['local_actions_block', 'local_tasks_block'])) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    $hide_on = [
      'user.login',
      'user.register',
      'user.pass',
    ];
    // Delete local actions, tabs from user.login... page.
    if (in_array($route_name, $hide_on)) {
      return AccessResult::forbidden();
    }
  }
  return AccessResult::neutral();
}

