# Schema for the configuration files of the person module.
dsi_contract.settings:
  type: config_object
  label: 'Contract settings'
  mapping:
    encoding_rules:
      type: string
      label: 'Encoding rules'
