dsi_device_other_subtype.oslc.*:
  type: config_entity
  label: 'Location choices config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
