<?php

/**
 * @file
 * Contains dsi_record.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dsi_client\Entity\ClientType;

/**
 * Implements hook_help().
 */
function dsi_record_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_record module.
    case 'help.page.dsi_record':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('待办事项。') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu__role_menu.
 */
function dsi_record_preprocess_menu__role_menu(&$variables) {
  $icons = [
    'entity.dsi_record.collection' => 'iconfont icon-rili',
  ];
  _eabax_core_set_menu_items_icon($variables['items'], $icons);
}

/**
 * Implements hook_theme().
 */
function dsi_record_theme() {
  return [
    'dsi_record_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_entity_operation().
 */
function dsi_record_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'dsi_client') {
    $operations = [];
    $operations['record'] = [
      'title' => t('Add Record', [], ['context' => 'Add todo']),
      'url' => \Drupal\Core\Url::fromRoute('entity.dsi_record.add_todo',[
        'entity_type' => $entity->getEntityTypeId(),
        'entity_id' => $entity->id()]
      ),
      'weight' => 0,
    ];

    return $operations;
  }
}

/**
 * Implements hook_entity_base_field_info() for client.
 */
function dsi_record_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'dsi_client') {
    $fields = [];
    $fields['record'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Record'))
      ->setSetting('target_type', 'dsi_record')
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_table',
        'weight' => 6,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
    return $fields;
  }
}
