<?php

/**
 * @file
 * Contains dsi_client.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dsi_client_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_client module.
    case 'help.page.dsi_client':
      $output = '';
      $output .= '<h3>' . t('Client') . '</h3>';
      $output .= '<p>' . t('The clients.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dsi_client_theme() {
  $theme = [];
  $theme['dsi_client'] = [
    'render element' => 'elements',
    'file' => 'dsi_client.page.inc',
  ];
  $theme['dsi_client_form'] = [
    'render element' => 'form',
  ];
  $theme['dsi_client_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'dsi_client.page.inc',
  ];
  $theme['client_intro_block'] = [
    'variables' => [ 'content' => NULL ],
    'render element' => 'children',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dsi_client_theme_suggestions_dsi_client(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#dsi_client'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'dsi_client__' . $sanitized_view_mode;
  $suggestions[] = 'dsi_client__' . $entity->bundle();
  $suggestions[] = 'dsi_client__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'dsi_client__' . $entity->id();
  $suggestions[] = 'dsi_client__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_crm_core_individual_label_alter().
 */
function dsi_client_crm_core_individual_label_alter(&$data, &$context1) {
  $data = $context1->field_person_name->value;
}

/**
 * Implements hook_record_entity_list_alter().
 */
function dsi_client_record_entity_list_alter(&$build = [], &$context1 = []) {
  $build['first']['client_intro'] = \Drupal::service('plugin.manager.block')->createInstance('client_intro_block', $context1)->build();
}
