<?php

namespace Drupal\eabax_workflows\Plugin\Menu\LocalAction;

use Drupal\Core\Cache\Cache;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\eabax_core\Plugin\Menu\LocalAction\AddDestination;

class TransitionApplyLocalAction extends AddDestination {

  /**
   * {@inheritdoc}
   */
  public function getRouteParameters(RouteMatchInterface $route_match) {
    // TODO: Change the autogenerated stub
    $route_parameters = parent::getRouteParameters($route_match);

    $entity = $route_match->getParameters()->all();
    $entity = reset($entity);
    $route_parameters['entity_id'] = $entity->id();

    return $route_parameters;
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheTags() {
    $route_match = \Drupal::routeMatch();
    $entity = $route_match->getParameters()->all();
    /** @var \Drupal\Core\Entity\EntityInterface $entity */
    $entity = reset($entity);
    $tags = Cache::mergeTags(parent::getCacheTags(), $entity->getCacheTags());

    return $tags;
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheContexts() {
    return Cache::mergeContexts(parent::getCacheContexts(), ['url']);
  }

}
