<?php

use Drupal\Core\Entity\ContentEntityTypeInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function entity_log_entity_insert(EntityInterface $entity) {
  $entity_type = $entity->getEntityType();

  if (!($entity_type instanceof ContentEntityTypeInterface)) {
    return;
  }

  $account = \Drupal::currentUser();

  \Drupal::database()->insert('entity_log')->fields([
    'uid' => $account->id(),
    'entity_type_id' => $entity->getEntityTypeId(),
    'entity_id' => $entity->id(),
    'message' => t('Add @entity_type : @entity', ['@entity_type' => $entity_type->getLabel(), '@entity' => $entity->label()]),
    'hostname' => \Drupal::request()->getClientIp(),
    'timestamp' => time(),
  ])->execute();
}

/**
 * Implements hook_entity_delete().
 */
function entity_log_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {

  $entity_type = $entity->getEntityType();

  if (!($entity_type instanceof ContentEntityTypeInterface)) {
    return;
  }

  $account = \Drupal::currentUser();

  \Drupal::database()->insert('entity_log')->fields([
    'uid' => $account->id(),
    'entity_type_id' => $entity->getEntityTypeId(),
    'entity_id' => $entity->id(),
    'message' => t('Delete @entity_type : @entity', ['@entity_type' => $entity_type->getLabel(), '@entity' => $entity->label()]),
    'hostname' => \Drupal::request()->getClientIp(),
    'timestamp' => time(),
  ])->execute();
}

/**
 * Implements hook_entity_update().
 */
function entity_log_entity_update(EntityInterface $entity) {
  if (!($entity->getEntityType() instanceof ContentEntityTypeInterface)) {
    return;
  }
  // 无orignal的原因：有可能是代码修改数据并保存，而不是界面修改数据并保存.
  if (!$entity->original) {
    return;
  }

  $account = \Drupal::currentUser();

  $field_definitions = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
  $messages = [];
  foreach ($field_definitions as $field_name => $field_definition) {
    if (in_array($field_name, ['langcode', 'created', 'changed', 'pinyin'])) {
      continue;
    }

    switch ($field_definition->getType()) {
      case 'entity_reference':
        $old_value = $entity->original->get($field_name)->target_id;
        $new_value = $entity->get($field_name)->target_id;
        if ($new_value != $old_value) {
          $message = $field_definition->getLabel() . ': ';
          if ($old_value && $old_target_entity = $entity->original->get($field_name)->entity) {
            $message .= $old_target_entity->label();
          }
          $message .= ' => ';
          if ($new_value && $new_target_entity = $entity->get($field_name)->entity) {
            $message .= $new_target_entity->label();
          }
          $messages[] = $message;
        }
        break;

      default:
        $old_value = $entity->original->get($field_name)->value;
        $new_value = $entity->get($field_name)->value;
        if ($new_value != $old_value) {
          if (is_array($new_value)) {
            $new_value = json_encode($new_value);
          }
          if (is_array($old_value)) {
            $old_value = json_encode($old_value);
          }
          $messages[] = $field_definition->getLabel() . ': ' . $old_value . ' => ' . $new_value;
        }
    }
  }

  if (!empty($messages)) {
    \Drupal::database()->insert('entity_log')->fields([
      'uid' => $account->id(),
      'entity_type_id' => $entity->getEntityTypeId(),
      'entity_id' => $entity->id(),
      'message' => implode(";\n", $messages),
      'hostname' => \Drupal::request()->getClientIp(),
      'timestamp' => time(),
    ])->execute();
  }
}
