field.storage_settings.code:
  type: field.storage_settings.string
  label: 'Code settings'
  mapping:
    encoding_rules:
      type: string
      label: 'Encoding rules'

field.value.code:
  type: field.value.string
