<?php

/**
 * @file
 * Provide functions for Drupal Materialize base theme.
 */

use DrupalCodeGenerator\Utils;

/**
 * Replace strings in a file.
 */
function materialize_helper_file_replace($file_path, $strings, $regexs = []) {
  $file_path = Utils::normalizePath($file_path);
  $file_contents = file_get_contents($file_path);

  if ($file_contents !== FALSE) {
    // Find text with strings.
    $find = array_keys($strings);
    $replace = $strings;
    $file_contents = str_replace($find, $replace, $file_contents);

    // Find text with regex.
    foreach ($regexs as $regex) {
      $file_contents = preg_replace($regex['pattern'], $regex['replacement'], $file_contents);
    }

    // Write to file.
    file_put_contents($file_path, $file_contents);
  }
}
